In [1]:
from utils_morpheus import *
from ProgramSpace import *

R[write to console]: 
Attaching package: ‘compare’


R[write to console]: The following object is masked from ‘package:base’:

    isTRUE


R[write to console]: 
Attaching package: ‘dplyr’


R[write to console]: The following objects are masked from ‘package:stats’:

    filter, lag


R[write to console]: The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union




In [13]:
len(CAMB_LIST)

574

In [2]:
m_interpreter = MorpheusInterpreter()
# m_spec = S.parse_file('./example/mChainOneNB.tyrell')
# m_spec = S.parse_file('./example/set_select.tyrell')
m_spec = S.parse_file('./example/camb2.tyrell')
m_eq = eq_r
m_generator = MorpheusGenerator(
    spec=m_spec,
    interpreter=m_interpreter,
    sfn=m_interpreter.sanity_check,
)

<bound method TyrellSpec.productions of <tyrell.spec.spec.TyrellSpec object at 0x118d7c438>>

In [8]:
dir(m_spec)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_enum_productions',
 '_add_param_productions',
 '_pred_spec',
 '_prod_spec',
 '_prog_spec',
 '_type_spec',
 'get_enum_production',
 'get_enum_production_or_raise',
 'get_function_production',
 'get_function_production_or_raise',
 'get_function_productions',
 'get_param_production',
 'get_param_production_or_raise',
 'get_param_productions',
 'get_predicates_with_name',
 'get_production',
 'get_production_or_raise',
 'get_productions_with_lhs',
 'get_type',
 'get_type_or_raise',
 'input',
 'name',
 'num_input',
 'num_predicates',
 'num_productions',
 'num_types',
 'output',
 'predicates',
 'product

In [3]:
b = m_interpreter.random_table()
b

'RET_DF2'

In [4]:
print(robjects.r(b))

  OCOL1  OCOL2 OCOL3      OCOL4
1   -48  18.82   -62   turdinae
2   -84 -74.56    67   scurries
3    38 -74.68     5 torrefying
4   -35  13.25   -39 torrefying
5   -84 -82.92    31   scurries
6   -17  22.81   -84  kyanising
7   -40  93.00    33  kyanising
8    84 -88.94   -88   turdinae



In [5]:
print(robjects.r(get_shadow_name(b)))

  X1 X2 X3 X4 X5 X6
1  0  0  0  0  0  0



In [11]:
# robjects.r("KKK <- select({},c(2,4))".format(b))
# robjects.r("KKK <- gather({},KEY,VAL,c(2,4))".format(b))
# robjects.r("KKK <- spread({},c(1),c(2))".format(b))
# robjects.r("KKK <- unite({},KEY,c(3),c(4))".format(b))
# robjects.r("KKK <- separate({},c(2),c('K1','K2'))".format(b))
robjects.r("KKK <- {} %>% mutate(KV=.[[2]]/.[[3]])".format(b))

R object with classes: ('data.frame',) mapped to:
[StrSexp..., FloatSe..., FloatSe..., FloatSe..., FloatSe...]
  OCOL1: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x1130aebc8> [RTYPES.STRSXP]
  OCOL2: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x1130ae208> [RTYPES.REALSXP]
  OCOL3: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x1130aebc8> [RTYPES.REALSXP]
  OCOL4: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x1130ae208> [RTYPES.REALSXP]
  KV: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x1130aebc8> [RTYPES.REALSXP]

In [12]:
print(robjects.r("KKK"))

       OCOL1  OCOL2 OCOL3  OCOL4          KV
1  submerged  76.87    -1 -89.33 -76.8700000
2       nibs  66.34    39 -18.40   1.7010256
3       nibs -31.09   -27 -27.44   1.1514815
4  submerged -43.65    12 -18.02  -3.6375000
5       nibs  56.19    25 -62.29   2.2476000
6       nibs -19.31    99 -41.38  -0.1950505
7 manifestos   7.25    24 -66.98   0.3020833
8       nibs -66.55   -64  41.88   1.0398437
9       soke  76.30    84  14.19   0.9083333



In [13]:
ma,mb,mc,md,ms,mi=camb_get_features(b,"KKK",verbose=False)

In [15]:
CAMB_LIST[595], CAMB_LIST[596], CAMB_LIST[597], CAMB_LIST[598], CAMB_LIST[599]

('<IVL/UNK>', '<IVL/NEG1>', '<IVL/NEG0>', '<IVL/POS0>', '<IVL/POS1>')

In [14]:
mi

array([[595., 599., 596., 596., 596.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [595., 599., 599., 596., 599.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [595., 596., 596., 596., 599.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [595., 596., 599., 596., 596.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [595., 599., 599., 596., 599.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [595., 596., 599., 596., 597.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [595., 599., 599., 596., 598.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [595., 596., 596., 599., 599.,   0

In [11]:
CAMB_LIST[4],CAMB_LIST[574]

('<COL_0>', '<RNK_UNK>')

In [15]:
mb

array([[  4.,   5., 166.,   8.,   9.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  4.,   5., 166.,   8.,   9.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  4.,   5., 166.,   8.,   9.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  4.,   5., 166.,   8.,   9.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  4.,   5., 166.,   8.,   9.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  4.,   5., 166.,   8.,   9.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  4.,   5., 166.,   8.,   9.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  4.,   5., 166.,   8.,   9.,   0

In [9]:
print(u[:10,:8])

[[  1.   1.   1.   1.   1.   0.   0.   0.]
 [ 33. 114. 114.  35.  36.   0.   0.   0.]
 [ 33. 114. 114.  35.  36.   0.   0.   0.]
 [ 33. 174. 114.  35.  36.   0.   0.   0.]
 [ 33. 114. 114.  35.  36.   0.   0.   0.]
 [ 33. 114. 114.  35.  36.   0.   0.   0.]
 [ 33. 174. 174.  35.  36.   0.   0.   0.]
 [ 33. 174. 174.  35.  36.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]]


In [12]:
CAMB_LIST[114],CAMB_LIST[174]

('<bSUB_1>', '<bSUB_DUP>')

In [22]:
while True:
    p_prog, p_example = m_generator.generate(
                        fixed_depth=4,
                        example=Example(input=[b], output=None),
    )
    if p_prog is not None:
        break

In [8]:
p_prog

ApplyNode(select, [ApplyNode(spread, [ApplyNode(gather, [ParamNode(0), AtomNode(['1', '3'])]), AtomNode(3), AtomNode(4)]), AtomNode(['3'])])

In [19]:
str(p_prog)

"gather(spread(select(@param0, ['3', '4']), 1, 2), ['3'])"

In [21]:
str(p_prog)

"gather(select(spread(@param0, 2, 4), ['3', '5']), ['2'])"

In [23]:
str(p_prog)

"select(spread(select(@param0, ['2', '3']), 1, 2), ['5'])"

In [9]:
p_prog.__repr__().count("ApplyNode")

2

In [10]:
p_example

Example(input=['RET_DF3'], output='RET_DF6')

In [9]:
print(robjects.r(get_shadow_name(p_example.output)))

  X1 X2 X3 X4 V5
1  0  0  0  0  1



In [10]:
print(robjects.r(p_example.output))

  OCOL1       OCOL2 OCOL3 OCOL4        COL5
1    75    reductor    74    54   1.0135135
2   -16    promercy    26    54  -0.6153846
3   -16    reductor   -64    54   0.2500000
4   -41 chilogrammo     2    54 -20.5000000
5   -41    reductor   -63   -26   0.6507937



In [13]:
print(robjects.r('RET_DF5'))

    OCOL1 OCOL3 OCOL4     OCOL6   KEY  VALUE
1  -17.35    99   -19 ignomious OCOL2 -17.60
2  -13.42    61   -78  wagoners OCOL2  40.30
3   18.27    61   -66 treadmill OCOL2  19.00
4   17.24   -26   -96  wagoners OCOL2 -97.70
5  -76.71    -5    71 ignomious OCOL2 -49.69
6  -17.35    99   -19 ignomious OCOL5   1.20
7  -13.42    61   -78  wagoners OCOL5 -21.49
8   18.27    61   -66 treadmill OCOL5  88.04
9   17.24   -26   -96  wagoners OCOL5 -45.58
10 -76.71    -5    71 ignomious OCOL5  56.56



In [14]:
print(robjects.r('SHADOW5'))

  X1 X3 X4 X6 V5 V6
1  0  0  0  0  1  1
2  0  0  0  0  1  1
3  0  0  0  0  1  1
4  0  0  0  0  1  1
5  0  0  0  0  1  1

