In [1]:
from utils_morpheus import *
from ProgramSpace import *

R[write to console]: 
Attaching package: ‘compare’


R[write to console]: The following object is masked from ‘package:base’:

    isTRUE


R[write to console]: 
Attaching package: ‘dplyr’


R[write to console]: The following objects are masked from ‘package:stats’:

    filter, lag


R[write to console]: The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union




In [25]:
m_interpreter = MorpheusInterpreter()
m_spec = S.parse_file('./example/set_mutate.tyrell')
m_eq = eq_r
m_generator = MorpheusGenerator(
    spec=m_spec,
    interpreter=m_interpreter,
    sfn=m_interpreter.sanity_check,
)

In [26]:
m_input = m_interpreter.random_table()
m_sample = m_generator.generate(
    fixed_depth=2,
    example=Example(input=[m_input],output=None)
)

In [27]:
m_sample

(ApplyNode(mutate, [ParamNode(0), AtomNode(/), AtomNode(5), AtomNode(5)]),
 Example(input=['RET_DF5'], output='RET_DF6'))

In [29]:
m_prog=m_sample[0]
m_prog

ApplyNode(mutate, [ParamNode(0), AtomNode(/), AtomNode(5), AtomNode(5)])

In [30]:
m_prog.name

'mutate'

In [32]:
m_prog.args

[ParamNode(0), AtomNode(/), AtomNode(5), AtomNode(5)]

In [36]:
m_prog.children[2].data

'5'

In [21]:
morpheus_cheating(m_sample[1].input[0],m_sample[1].output)

[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]

In [17]:
m_sample[1].input[0]

'RET_DF5'

In [2]:
a = MorpheusInterpreter()

In [4]:
b = a.random_table()

In [5]:
print(robjects.r(b))

        OCOL1  OCOL2 OCOL3
1    cuddlier -88.35     9
2    cuddlier  20.78   -40
3    cuddlier  57.33   -46
4 subcolumnar -25.99   -12
5    cuddlier -83.73   -49



In [6]:
robjects.r("KKK <- select({},c(1,2))".format(b))

R object with classes: ('data.frame',) mapped to:
[StrSexpVector, FloatSexpVector]
  OCOL1: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x116309488> [RTYPES.STRSXP]
  OCOL2: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x116309708> [RTYPES.REALSXP]

In [7]:
print(robjects.r("KKK"))

        OCOL1  OCOL2
1    cuddlier -88.35
2    cuddlier  20.78
3    cuddlier  57.33
4 subcolumnar -25.99
5    cuddlier -83.73



In [9]:
len(morpheus_set1(b, "KKK", verbose=True))

642

In [5]:
robjects.r("KKK <- summarise({},KEY=max(OCOL3))".format(b))

R object with classes: ('data.frame',) mapped to:
[FloatSexpVector]
  KEY: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x11bc1e3c8> [RTYPES.REALSXP]

In [6]:
print(robjects.r("KKK"))

  KEY
1  90



In [7]:
morpheus_summarise(b, "KKK", verbose=True)

[(87.87, -77.24, {68.32, 40.92, -18.94, -77.24, -76.66, -44.92, 87.87, -71.2, -67.65}), None, (90.0, -91.0, {64.0, -91.0, 7.0, 72.0, 77.0, 14.0, 18.0, 90.0, -35.0}), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]


[True,
 True,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [22]:
robjects.r("KKK <- mutate({},KEY=OCOL1/OCOL3)".format(b))

R object with classes: ('data.frame',) mapped to:
[Floa..., StrS..., Floa..., Floa..., StrS..., Floa..., Floa...]
  OCOL1: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x109cc4dc8> [RTYPES.REALSXP]
  OCOL2: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x109cc4e48> [RTYPES.STRSXP]
  OCOL3: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x109cc4b48> [RTYPES.REALSXP]
  OCOL4: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x109cc4e48> [RTYPES.REALSXP]
  OCOL5: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x109cc4b48> [RTYPES.STRSXP]
  OCOL6: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x109ccb108> [RTYPES.REALSXP]
  KEY: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x109cc4b48> [RTYPES.REALSXP]

In [23]:
print(robjects.r("KKK"))

   OCOL1           OCOL2 OCOL3  OCOL4         OCOL5 OCOL6        KEY
1 -45.25          ararao   -99 -42.44 discomycetous    81  0.4570707
2  39.42 superinnocently   -77  75.47        rubian    90 -0.5119481
3  59.44          ararao  -100  30.67    demicircle    18 -0.5944000
4 -98.77        frounced    85 -78.87        rubian    31 -1.1620000
5  17.60        frounced  -100 -39.95        rubian   -78 -0.1760000
6 -66.70 superinnocently   -77 -24.56 discomycetous    43  0.8662338



In [24]:
morpheus_mutate(b, "KKK", verbose=True)

[0.9999999999999999,
 0,
 -0.9999999999999999,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [16]:
robjects.r("KKK <- {} %>% filter(.[[1]] < 2)".format(b))

R object with classes: ('data.frame',) mapped to:
[FloatSe..., StrSexp..., StrSexp..., StrSexp..., FloatSe...]
  OCOL1: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x11b7de1c8> [RTYPES.REALSXP]
  OCOL2: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x11b7de208> [RTYPES.STRSXP]
  OCOL3: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x11b7dec48> [RTYPES.STRSXP]
  OCOL4: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x11b7de488> [RTYPES.STRSXP]
  OCOL5: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x11b7deb08> [RTYPES.REALSXP]

In [17]:
print(robjects.r("KKK"))

  OCOL1             OCOL2          OCOL3      OCOL4 OCOL5
1   -22  superlaryngeally       comatose fantasying   -13
2   -21         deadbeats        roomful hydrocycle   -99
3   -21     demineralizer       comatose fantasying   -70
4   -21          discrive nondefalcation hydrocycle   -18
5   -22       interveinal nondefalcation hydrocycle    -8
6   -21 demonstratability nondefalcation hydrocycle     1



In [18]:
morpheus_filter(b, "KKK", verbose=True)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [10]:
robjects.r("KKK <- separate({},c(1),c('key1','key2'))".format(b))

R object with classes: ('data.frame',) mapped to:
[StrSexp..., StrSexp..., StrSexp..., FloatSe..., FloatSe...]
  key1: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x10c055188> [RTYPES.STRSXP]
  key2: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x10c055e48> [RTYPES.STRSXP]
  OCOL2: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x10c055108> [RTYPES.STRSXP]
  OCOL3: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x10c055188> [RTYPES.REALSXP]
  OCOL4: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x10c055e48> [RTYPES.REALSXP]

In [11]:
print(robjects.r("KKK"))

              key1 key2          OCOL2 OCOL3 OCOL4
1 metabolizability <NA>       capmaker   -31   -89
2          hurdler <NA>      socotrine   -33    48
3       marssonina <NA> immunoreaction   -79   -26
4       understand <NA>         catgut     4    51
5       stupefying <NA> unpathetically    92   -26
6             pars <NA>    overfreedom   -46    72
7        vitelline <NA>           gauk    96   -26



In [12]:
morpheus_separate(b, "KKK", verbose=True)

[0.0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [9]:
robjects.r("PPP <- unite({},KEY,c(1),c(2))".format(b))

R object with classes: ('data.frame',) mapped to:
[StrSexpVec..., StrSexpVec..., StrSexpVec..., FloatSexpV...]
  KEY: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x117824b88> [RTYPES.STRSXP]
  OCOL3: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x115b3e608> [RTYPES.STRSXP]
  OCOL4: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x117824b88> [RTYPES.STRSXP]
  OCOL5: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x115b3e688> [RTYPES.REALSXP]

In [10]:
print(robjects.r("PPP"))

                                KEY        OCOL3     OCOL4 OCOL5
1     hyperprophetic_unadulterously      fiddled   consort     3
2 hyperprophetic_nonargumentatively      fiddled boerhavia   -86
3      overemulating_unadulterously prosilverite    hybrid     3
4       pentacoccous_unadulterously      fiddled    hybrid     3
5          lintelled_unadulterously prosilverite boerhavia   -86
6       pentacoccous_unadulterously prosilverite    hybrid   -57
7          lintelled_unadulterously   graybeards   consort   -57
8          baryphony_unadulterously prosilverite boerhavia     3
9      overemulating_unadulterously      fiddled    hybrid     3



In [11]:
robjects.r("KKK <- separate({},c(1),c('key1','key2'))".format("PPP"))

R object with classes: ('data.frame',) mapped to:
[StrSexp..., StrSexp..., StrSexp..., StrSexp..., FloatSe...]
  key1: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x115b3e208> [RTYPES.STRSXP]
  key2: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x115b3e548> [RTYPES.STRSXP]
  OCOL3: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x115b3e8c8> [RTYPES.STRSXP]
  OCOL4: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x115b3e208> [RTYPES.STRSXP]
  OCOL5: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x115b3e548> [RTYPES.REALSXP]

In [12]:
print(robjects.r("KKK"))

            key1               key2        OCOL3     OCOL4 OCOL5
1 hyperprophetic     unadulterously      fiddled   consort     3
2 hyperprophetic nonargumentatively      fiddled boerhavia   -86
3  overemulating     unadulterously prosilverite    hybrid     3
4   pentacoccous     unadulterously      fiddled    hybrid     3
5      lintelled     unadulterously prosilverite boerhavia   -86
6   pentacoccous     unadulterously prosilverite    hybrid   -57
7      lintelled     unadulterously   graybeards   consort   -57
8      baryphony     unadulterously prosilverite boerhavia     3
9  overemulating     unadulterously      fiddled    hybrid     3



In [13]:
morpheus_separate("PPP", "KKK", verbose=True)

[[['hyperprophetic', 'unadulterously'], ['fiddled'], ['consort'], ['3']], [['hyperprophetic', 'nonargumentatively'], ['fiddled'], ['boerhavia'], ['-86']], [['overemulating', 'unadulterously'], ['prosilverite'], ['hybrid'], ['3']], [['pentacoccous', 'unadulterously'], ['fiddled'], ['hybrid'], ['3']], [['lintelled', 'unadulterously'], ['prosilverite'], ['boerhavia'], ['-86']], [['pentacoccous', 'unadulterously'], ['prosilverite'], ['hybrid'], ['-57']], [['lintelled', 'unadulterously'], ['graybeards'], ['consort'], ['-57']], [['baryphony', 'unadulterously'], ['prosilverite'], ['boerhavia'], ['3']], [['overemulating', 'unadulterously'], ['fiddled'], ['hybrid'], ['3']]]


[2.0000000000000004,
 0.0,
 0.0,
 0.0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [6]:
robjects.r("KKK <- unite({},KEY,c(1),c(4))".format(b))

R object with classes: ('data.frame',) mapped to:
[StrSexpVec..., StrSexpVec..., StrSexpVec..., FloatSexpV...]
  KEY: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x1156b8b88> [RTYPES.STRSXP]
  OCOL2: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x1156b8f48> [RTYPES.STRSXP]
  OCOL3: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x1139e9988> [RTYPES.STRSXP]
  OCOL5: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x1156b8f48> [RTYPES.REALSXP]

In [7]:
print(robjects.r("KKK"))

      KEY    OCOL2       OCOL3 OCOL5
1   63_22 statutes   ambulated    57
2 -23_-60 statutes    apologer   -27
3  -81_85   withal    apologer   -96
4  72_-96   withal    apologer   -52
5   90_39   withal    apologer    26
6 -74_-59 statutes etiophyllin   -62
7   28_36 statutes   ambulated   -32
8 -59_-20   withal    apologer    48
9  81_-90 statutes    apologer   -27



In [8]:
morpheus_unite(b, "KKK", verbose=True)

[1.1111111111111112,
 0,
 0,
 2.0000000000000004,
 0.2222222222222222,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [6]:
robjects.r("KKK <- spread({},c(2),c(3))".format(b))

R object with classes: ('data.frame',) mapped to:
[FloatSexp..., StrSexpVe..., FloatSexp..., FloatSexp..., ..., FloatSexp..., FloatSexp..., FloatSexp..., FloatSexp...]
  OCOL1: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
[-91.000000, -3.000000, 25.000000, 25.000000, 85.000000, 85.000000, 85.000000]
  OCOL4: <class 'rpy2.robjects.vectors.StrVector'>
  R object with classes: ('character',) mapped to:
['qui..., 'rei..., 'qui..., 'rei..., 'gen..., 'gen..., 'rei...]
  OCOL5: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
[79.000000, -38.000000, -38.000000, -38.000000, -38.000000, 98.000000, 98.000000]
  bephrase: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
[     nan,      nan,      nan,      nan,      nan,      nan, 6.000000]
...
  chirotype: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
[89.000000,      nan,      nan,      nan,      nan,      nan,      nan]
  jiminy: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
[     nan,      nan, 77.000000,      nan,      nan,      nan,      nan]
  noncommemoratively: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
[     nan,      nan,      nan,      nan,      nan, 96.000000,      nan]
  spirital: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
[     nan, 70.000000,      nan,      nan,      nan,      nan,      nan]

In [8]:
len(morpheus_set1(b, "KKK", verbose=True))

/Users/joseph/Desktop/UCSB/19spring/Research_Feng/Trinity/utils_morpheus.py:1008: RuntimeWarning: invalid value encountered in equal
  if np0_obj[j,i] in np1_obj[:,k]:


80

In [34]:
morpheus_spread(b, "KKK", verbose=True)

/Users/joseph/Desktop/UCSB/19spring/Research_Feng/Trinity/utils_morpheus.py:1008: RuntimeWarning: invalid value encountered in equal
  if np0_obj[j,i] in np1_obj[:,k]:


[0,
 1.0000000000000002,
 0.1111111111111111,
 0.5555555555555556,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0.1111111111111111,
 1.0000000000000002,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [12]:
a.print_cmp("KKK")

      OCOL1 -86  -81  -59  -39  -32  -16   20    25    99  
 [1,] "-69" NA   NA   NA   NA   NA   "-88" NA    NA    NA  
 [2,] "-35" NA   "20" NA   NA   NA   NA    NA    NA    NA  
 [3,] "-21" NA   NA   NA   NA   NA   NA    NA    NA    "52"
 [4,] "0"   NA   NA   "22" NA   NA   NA    NA    NA    NA  
 [5,] "27"  "80" NA   NA   NA   NA   NA    NA    NA    NA  
 [6,] "28"  NA   NA   NA   NA   NA   NA    NA    "100" NA  
 [7,] "36"  NA   NA   NA   NA   NA   NA    "-84" NA    NA  
 [8,] "81"  NA   NA   NA   "51" NA   NA    NA    NA    NA  
 [9,] "82"  NA   NA   NA   NA   "12" NA    NA    NA    NA  



In [9]:
morpheus_cheating("RET_DF2","KKK")

[1, 1, 0, 0, 1, 0, 0, 0, 0, 0]

In [9]:
len(morpheus_abstraction("KKK",verbose=True))

existence_row: [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
existence_col: [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_string_col: [1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_float_col: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_int_col: [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
categorical_col: [0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
separator_col: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
string_hashing_cell: [[0.0204 0.6735 0.2245 0.     0.6531]
 [0.0204 0.6735 0.6531 0.     0.6531]
 [0.0204 0.6735 0.6531 0.     0.2245]
 [0.0204 0.6735 0.3673 0.     0.6531]
 [0.0204 0.5306 0.6531 0.     0.2245]]
float_hashing_cell: [[0.   0.   0.   0.61 0.  ]
 [0.   0.   0.   0.11 0.  ]
 [0.   0.   0.   0.81 0.  ]
 [0.   0.   0.   0.81 0.  ]
 [0.   0.   0.   0.71 0.  ]]


155

In [5]:
len(morpheus_abstraction(b,verbose=True))

existence_row: [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
existence_col: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_string_col: [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_float_col: [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_int_col: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
categorical_col: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
separator_col: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
string_hashing_cell: [[0.3061 0.     0.3061 0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.    ]
 [0.2245 0.     0.2245 0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.    ]
 [0.6122 0.     0.2449 0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.    ]
 [0.2449 0.     0.2041 0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.    ]
 [0.6531 0.     0.5918 0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.    ]
 [0.1633 0.     0.

555

In [11]:
nb = numpy.asarray(robjects.r(b),dtype=numpy.object).T

In [33]:
nb[:,1].tolist()

[-18.0, -88.0, 1.0, 1.0, -88.0, -88.0, 1.0, -18.0]

In [18]:
type(nb[0,0])

float

In [31]:
int(nb[0,2])==nb[0,0]

False

In [28]:
isinstance(nb[0,0],numpy.int)

False

In [26]:
isinstance(nb[0,3],numpy.str)

True

In [23]:
robjects.r("sapply({},class)".format(b))

R object with classes: ('character',) mapped to:
['numeric', 'numeric', 'numeric', 'character']

In [34]:
"fsdfLKJEFWElfkjwe".lower()

'fsdflkjefwelfkjwe'

In [35]:
type(nb)

numpy.ndarray