In [1]:
from utils_morpheus import *
from ProgramSpace import *

R[write to console]: 
Attaching package: ‘compare’


R[write to console]: The following object is masked from ‘package:base’:

    isTRUE


R[write to console]: 
Attaching package: ‘dplyr’


R[write to console]: The following objects are masked from ‘package:stats’:

    filter, lag


R[write to console]: The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union




In [2]:
a = MorpheusInterpreter()

In [3]:
b = a.random_table()

In [4]:
print(robjects.r(b))

             OCOL1  OCOL2          OCOL3
1      insalubrity -76.95 galactotherapy
2         acneform  30.13  extrospection
3    semiaperiodic   9.65       decipher
4           bowpot -94.87       clogging
5          randall -87.04       sempstry
6 aerobacteriology -94.35   pentavalency
7       antiknocks  18.02     foliaceous



In [6]:
robjects.r("KKK <- unite({},KEY,c(1,2))".format(b))

R object with classes: ('data.frame',) mapped to:
[StrSexp..., StrSexp..., StrSexp..., FloatSe..., StrSexp...]
  KEY: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x108d2c388> [RTYPES.STRSXP]
  OCOL3: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x10e8e2088> [RTYPES.STRSXP]
  OCOL4: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x108d2c388> [RTYPES.STRSXP]
  OCOL5: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x10e8e2cc8> [RTYPES.REALSXP]
  OCOL6: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x108d2c388> [RTYPES.STRSXP]

In [9]:
len(morpheus_abstraction("KKK",verbose=True))

existence_row: [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
existence_col: [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_string_col: [1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_float_col: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_int_col: [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
categorical_col: [0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
separator_col: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
string_hashing_cell: [[0.0204 0.6735 0.2245 0.     0.6531]
 [0.0204 0.6735 0.6531 0.     0.6531]
 [0.0204 0.6735 0.6531 0.     0.2245]
 [0.0204 0.6735 0.3673 0.     0.6531]
 [0.0204 0.5306 0.6531 0.     0.2245]]
float_hashing_cell: [[0.   0.   0.   0.61 0.  ]
 [0.   0.   0.   0.11 0.  ]
 [0.   0.   0.   0.81 0.  ]
 [0.   0.   0.   0.81 0.  ]
 [0.   0.   0.   0.71 0.  ]]


155

In [5]:
len(morpheus_abstraction(b,verbose=True))

existence_row: [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
existence_col: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_string_col: [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_float_col: [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_int_col: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
categorical_col: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
separator_col: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
string_hashing_cell: [[0.3061 0.     0.3061 0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.    ]
 [0.2245 0.     0.2245 0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.    ]
 [0.6122 0.     0.2449 0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.    ]
 [0.2449 0.     0.2041 0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.    ]
 [0.6531 0.     0.5918 0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.    ]
 [0.1633 0.     0.

555

In [11]:
nb = numpy.asarray(robjects.r(b),dtype=numpy.object).T

In [33]:
nb[:,1].tolist()

[-18.0, -88.0, 1.0, 1.0, -88.0, -88.0, 1.0, -18.0]

In [18]:
type(nb[0,0])

float

In [31]:
int(nb[0,2])==nb[0,0]

False

In [28]:
isinstance(nb[0,0],numpy.int)

False

In [26]:
isinstance(nb[0,3],numpy.str)

True

In [23]:
robjects.r("sapply({},class)".format(b))

R object with classes: ('character',) mapped to:
['numeric', 'numeric', 'numeric', 'character']

In [34]:
"fsdfLKJEFWElfkjwe".lower()

'fsdflkjefwelfkjwe'

In [35]:
type(nb)

numpy.ndarray