In [1]:
from utils_morpheus import *
from ProgramSpace import *

R[write to console]: 
Attaching package: ‘compare’


R[write to console]: The following object is masked from ‘package:base’:

    isTRUE


R[write to console]: 
Attaching package: ‘dplyr’


R[write to console]: The following objects are masked from ‘package:stats’:

    filter, lag


R[write to console]: The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union




In [2]:
a = MorpheusInterpreter()

In [3]:
b = a.random_table()

In [6]:
b

'RET_DF2'

In [4]:
print(robjects.r(b))

  OCOL1  OCOL2 OCOL3 OCOL4           OCOL5
1   -36 -52.74   -42    92         seafare
2   -73 -54.35  -100    18   odontognathic
3    99 -21.21  -100   -58         alleleu
4   -80  -2.70   -42    51      mohammedan
5    69  83.22  -100   -41      galeodidae
6    51  93.34  -100    92        clitella
7   -77 -10.98  -100   -79 preachification
8    74 -11.96   -42   -44          eerier



In [8]:
robjects.r("KKK <- select({},c(1,2,5))".format(b))

R object with classes: ('data.frame',) mapped to:
[FloatSexpVector, FloatSexpVector, StrSexpVector]
  OCOL1: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x108ef3608> [RTYPES.REALSXP]
  OCOL2: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x108ef3c08> [RTYPES.REALSXP]
  OCOL5: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x108ef3b48> [RTYPES.STRSXP]

In [9]:
morpheus_cheating("RET_DF2","KKK")

[1, 1, 0, 0, 1, 0, 0, 0, 0, 0]

In [9]:
len(morpheus_abstraction("KKK",verbose=True))

existence_row: [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
existence_col: [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_string_col: [1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_float_col: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_int_col: [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
categorical_col: [0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
separator_col: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
string_hashing_cell: [[0.0204 0.6735 0.2245 0.     0.6531]
 [0.0204 0.6735 0.6531 0.     0.6531]
 [0.0204 0.6735 0.6531 0.     0.2245]
 [0.0204 0.6735 0.3673 0.     0.6531]
 [0.0204 0.5306 0.6531 0.     0.2245]]
float_hashing_cell: [[0.   0.   0.   0.61 0.  ]
 [0.   0.   0.   0.11 0.  ]
 [0.   0.   0.   0.81 0.  ]
 [0.   0.   0.   0.81 0.  ]
 [0.   0.   0.   0.71 0.  ]]


155

In [5]:
len(morpheus_abstraction(b,verbose=True))

existence_row: [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
existence_col: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_string_col: [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_float_col: [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
type_int_col: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
categorical_col: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
separator_col: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
string_hashing_cell: [[0.3061 0.     0.3061 0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.    ]
 [0.2245 0.     0.2245 0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.    ]
 [0.6122 0.     0.2449 0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.    ]
 [0.2449 0.     0.2041 0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.    ]
 [0.6531 0.     0.5918 0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.    ]
 [0.1633 0.     0.

555

In [11]:
nb = numpy.asarray(robjects.r(b),dtype=numpy.object).T

In [33]:
nb[:,1].tolist()

[-18.0, -88.0, 1.0, 1.0, -88.0, -88.0, 1.0, -18.0]

In [18]:
type(nb[0,0])

float

In [31]:
int(nb[0,2])==nb[0,0]

False

In [28]:
isinstance(nb[0,0],numpy.int)

False

In [26]:
isinstance(nb[0,3],numpy.str)

True

In [23]:
robjects.r("sapply({},class)".format(b))

R object with classes: ('character',) mapped to:
['numeric', 'numeric', 'numeric', 'character']

In [34]:
"fsdfLKJEFWElfkjwe".lower()

'fsdflkjefwelfkjwe'

In [35]:
type(nb)

numpy.ndarray