In [1]:
from utils_morpheus import *
from ProgramSpace import *

R[write to console]: 
Attaching package: ‘compare’


R[write to console]: The following object is masked from ‘package:base’:

    isTRUE


R[write to console]: 
Attaching package: ‘dplyr’


R[write to console]: The following objects are masked from ‘package:stats’:

    filter, lag


R[write to console]: The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union




In [2]:
m_interpreter = MorpheusInterpreter()
m_spec = S.parse_file('./example/set1.tyrell')
m_eq = eq_r
m_generator = MorpheusGenerator(
    spec=m_spec,
    interpreter=m_interpreter,
    sfn=m_interpreter.sanity_check,
)

In [3]:
b = m_interpreter.random_table()
b

'RET_DF2'

In [4]:
print(robjects.r(b))

         OCOL1  OCOL2     OCOL3 OCOL4        OCOL5 OCOL6
1   reunionism  17.63 recharted    90 concupiscent     0
2       causey -11.46 recharted   -68   unculpable   -80
3  hypothesist   8.35  korahite    90    cockscomb     5
4       causey -86.10 recharted   -85    cockscomb    44
5   reunionism -57.19 recharted   -49    cockscomb   -57
6       causey -80.83 recharted   -49   unculpable    70
7       causey   7.53 recharted   -49    cockscomb    49
8       causey -24.26  korahite   -85    cockscomb   -17
9       causey  54.93  korahite    90      phacoid    81
10  reunionism  -6.39  korahite   -85      phacoid    19



In [7]:
# robjects.r("KKK <- select({},c(2,4))".format(b))
robjects.r("KKK <- gather({},KEY,VAL,c(2,4))".format(b))
# robjects.r("KKK <- spread({},c(1),c(2))".format(b))

R object with classes: ('data.frame',) mapped to:
[StrSe..., StrSe..., StrSe..., Float..., StrSe..., Float...]
  OCOL1: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x10c1e2a88> [RTYPES.STRSXP]
  OCOL3: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x10c1e2a08> [RTYPES.STRSXP]
  OCOL5: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x10c1e2a88> [RTYPES.STRSXP]
  OCOL6: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x10c1e2a08> [RTYPES.REALSXP]
  KEY: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x10c1e2a88> [RTYPES.STRSXP]
  VAL: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x10e338188> [RTYPES.REALSXP]

In [8]:
print(robjects.r("KKK"))

         OCOL1     OCOL3        OCOL5 OCOL6   KEY    VAL
1   reunionism recharted concupiscent     0 OCOL2  17.63
2       causey recharted   unculpable   -80 OCOL2 -11.46
3  hypothesist  korahite    cockscomb     5 OCOL2   8.35
4       causey recharted    cockscomb    44 OCOL2 -86.10
5   reunionism recharted    cockscomb   -57 OCOL2 -57.19
6       causey recharted   unculpable    70 OCOL2 -80.83
7       causey recharted    cockscomb    49 OCOL2   7.53
8       causey  korahite    cockscomb   -17 OCOL2 -24.26
9       causey  korahite      phacoid    81 OCOL2  54.93
10  reunionism  korahite      phacoid    19 OCOL2  -6.39
11  reunionism recharted concupiscent     0 OCOL4  90.00
12      causey recharted   unculpable   -80 OCOL4 -68.00
13 hypothesist  korahite    cockscomb     5 OCOL4  90.00
14      causey recharted    cockscomb    44 OCOL4 -85.00
15  reunionism recharted    cockscomb   -57 OCOL4 -49.00
16      causey recharted   unculpable    70 OCOL4 -49.00
17      causey recharted    coc

In [13]:
robjects.r("LLL <- select(KKK,c(5,6))".format(b))

R object with classes: ('data.frame',) mapped to:
[StrSexpVector, FloatSexpVector]
  KEY: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x10e338b08> [RTYPES.STRSXP]
  VAL: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x10e338cc8> [RTYPES.REALSXP]

In [14]:
print(robjects.r("LLL"))

     KEY    VAL
1  OCOL2  17.63
2  OCOL2 -11.46
3  OCOL2   8.35
4  OCOL2 -86.10
5  OCOL2 -57.19
6  OCOL2 -80.83
7  OCOL2   7.53
8  OCOL2 -24.26
9  OCOL2  54.93
10 OCOL2  -6.39
11 OCOL4  90.00
12 OCOL4 -68.00
13 OCOL4  90.00
14 OCOL4 -85.00
15 OCOL4 -49.00
16 OCOL4 -49.00
17 OCOL4 -49.00
18 OCOL4 -85.00
19 OCOL4  90.00
20 OCOL4 -85.00



In [7]:
CMM_DICT

{'<COL_0>': 7,
 '<COL_10>': 17,
 '<COL_11>': 18,
 '<COL_12>': 19,
 '<COL_13>': 20,
 '<COL_14>': 21,
 '<COL_15>': 22,
 '<COL_16>': 23,
 '<COL_17>': 24,
 '<COL_18>': 25,
 '<COL_19>': 26,
 '<COL_1>': 8,
 '<COL_2>': 9,
 '<COL_3>': 10,
 '<COL_4>': 11,
 '<COL_5>': 12,
 '<COL_6>': 13,
 '<COL_7>': 14,
 '<COL_8>': 15,
 '<COL_9>': 16,
 '<DUP>': 2,
 '<NEW>': 1,
 '<OUT>': 3,
 '<PAD>': 0,
 '<rCOL_0>': 27,
 '<rCOL_10>': 37,
 '<rCOL_11>': 38,
 '<rCOL_12>': 39,
 '<rCOL_13>': 40,
 '<rCOL_14>': 41,
 '<rCOL_15>': 42,
 '<rCOL_16>': 43,
 '<rCOL_17>': 44,
 '<rCOL_18>': 45,
 '<rCOL_19>': 46,
 '<rCOL_1>': 28,
 '<rCOL_2>': 29,
 '<rCOL_3>': 30,
 '<rCOL_4>': 31,
 '<rCOL_5>': 32,
 '<rCOL_6>': 33,
 '<rCOL_7>': 34,
 '<rCOL_8>': 35,
 '<rCOL_9>': 36,
 '<rDUP>': 5,
 '<rNEW>': 4,
 '<rOUT>': 6}

In [12]:
u=morpheus_select_cmm(b,"KKK",verbose=True)

[[ 4.  4.  4. ...  0.  0.  0.]
 [ 9. 10. 11. ...  0.  0.  0.]
 [ 9. 10. 11. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


In [15]:
print(u[:,:10])

[[ 4.  4.  4. 27. 27.  0.  0.  0.  0.  0.]
 [ 9. 10. 11.  3.  8.  0.  0.  0.  0.  0.]
 [ 9. 10. 11.  8.  3.  0.  0.  0.  0.  0.]
 [ 9. 10. 11.  8.  3.  0.  0.  0.  0.  0.]
 [ 9. 10. 11.  3.  8.  0.  0.  0.  0.  0.]
 [ 9. 10. 11.  8.  3.  0.  0.  0.  0.  0.]
 [ 9. 10. 11.  3.  8.  0.  0.  0.  0.  0.]
 [ 9. 10. 11.  3.  8.  0.  0.  0.  0.  0.]
 [ 9. 10. 11.  8.  3.  0.  0.  0.  0.  0.]
 [ 9. 10. 11.  8.  3.  0.  0.  0.  0.  0.]
 [ 9. 10. 11.  3.  8.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  